[package]
name = "solti-core"
description = "Solti SDK supervisor orchestration."

rust-version.workspace = true
repository.workspace = true
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
taskvisor   = { workspace = true, features = ["controller"] }
parking_lot = { workspace = true }
tokio-util  = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
tokio       = { workspace = true }

solti-model  = { workspace = true }
solti-runner = { workspace = true }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
