[package]
name = "solti-core"
version = "0.0.1"
edition = "2024"

[features]
default = []

[dependencies]
taskvisor = { workspace = true, features = ["controller"] }

async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }

parking_lot = { workspace = true }
solti-model = { path = "../solti-model" }

[dev-dependencies]
tokio-util = { workspace = true }
