[package]
name = "solti-discover"
version = "0.0.1"
edition = "2024"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
grpc = ["dep:tonic", "dep:tonic-prost", "dep:prost"]
http = ["dep:reqwest", "dep:serde_json", "dep:prost", "dep:pbjson"]

[dependencies]
pbjson = { workspace = true, optional = true }
prost = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["json"], optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
taskvisor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true, optional = true }
tonic-prost = { workspace = true, optional = true }
tracing = { workspace = true }

solti-core = { path = "../solti-core" }
solti-model = { path = "../solti-model" }

[build-dependencies]
pbjson-build = { workspace = true }
protoc-bin-vendored = { workspace = true }
tonic-prost-build = { workspace = true }
