[workspace]
members = [
    "crates/solti-prometheus",
    "crates/solti-discover",
    "crates/solti-observe",
    "crates/solti-model",
    "crates/solti-runner",
    "crates/solti-core",
    "crates/solti-exec",
    "crates/solti-api",

    "examples/agentd",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
tracing-subscriber = { version = "0.3" }
protoc-bin-vendored = { version = "3" }
tokio = { version = "1" }
tokio-util = "0.7.17"
time = { version = "0.3" }
serde = { version = "1", features = ["derive"] }
tracing-journald = "0.3.1"
taskvisor = { version = "0.1.1" }
prometheus = "0.14.0"
reqwest = "0.13.1"
async-trait = "0.1"
serde_json = "1"
thiserror = "2"
tracing = "0.1"
anyhow  = "1"
libc = "0.2.177"
base64 = "0.22"
axum = "0.8.7"
tower-http = "0.6"
hostname = "0.4.2"
uuid = "1.19.0"
parking_lot = "0.12"

tonic-prost-build = "0.14.5"
prost-types = "0.14.3"
tonic-prost = "0.14.5"
tonic = "0.14.5"
prost = "0.14.3"

pbjson-build = "0.9.0"
pbjson = "0.9.0"