[workspace]
members = [
    "crates/solti-prometheus",
    "crates/solti-discover",
    "crates/solti-observe",
    "crates/solti-model",
    "crates/solti-runner",
    "crates/solti-core",
    "crates/solti-exec",
    "crates/solti-api",
    "crates/solti-tls",

    "examples/agentd-http",
    "examples/agentd-grpc",
    "examples/tls-roundtrip",
]
resolver = "2"

[workspace.package]
version      = "0.0.3"
edition      = "2024"
rust-version = "1.90.0"
license      = "Apache-2.0"

repository   = "https://github.com/soltiHQ/sdk"
homepage     = "https://github.com/soltiHQ/sdk"

keywords     = ["async", "tasks", "supervisor", "orchestration", "solti"]
categories   = ["asynchronous", "concurrency"]

[workspace.dependencies]
anyhow              = "1.0.102"
async-trait         = "0.1.89"
axum                = "0.8.9"
base64              = "0.22.1"
bytes               = "1.12.0"
getrandom           = "0.4.3"
hostname            = "0.4.2"
http-body-util      = "0.1.3"
itoa                = "1.0.18"
libc                = "0.2.177"
parking_lot         = "0.12.5"
pbjson              = "0.9.0"
pbjson-build        = "0.9.0"
prometheus          = "0.14.0"
prost               = "0.14.4"
prost-types         = "0.14.4"
protoc-bin-vendored = { version = "3.2.0" }
rcgen               = "0.14.8"
reqwest             = "0.13.4"
rustls              = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-pemfile      = "2.2.0"
serde               = { version = "1.0.228", features = ["derive"] }
serde_json          = "1.0.150"
subtle              = "2.6.1"
taskvisor           = { version = "0.3.0" }
tempfile            = "3.27.0"
thiserror           = "2.0.18"
time                = { version = "0.3.49" }
tokio               = { version = "1.52.3" }
tokio-rustls        = { version = "0.26.4", default-features = false, features = ["ring", "tls12"] }
tokio-stream        = "0.1.18"
tokio-util          = "0.7.18"
tonic               = "0.14.6"
tonic-prost         = "0.14.6"
tonic-prost-build   = "0.14.6"
tower               = "0.5.3"
tower-http          = "0.7.0"
tracing             = "0.1.44"
tracing-journald    = "0.3.2"
tracing-subscriber  = { version = "0.3.23" }
uuid                = "1.23.1"

solti-tls        = { path = "crates/solti-tls",        version = "0.0.3" }
solti-model      = { path = "crates/solti-model",      version = "0.0.3" }
solti-runner     = { path = "crates/solti-runner",     version = "0.0.3" }
solti-exec       = { path = "crates/solti-exec",       version = "0.0.3" }
solti-core       = { path = "crates/solti-core",       version = "0.0.3" }
solti-api        = { path = "crates/solti-api",        version = "0.0.3" }
solti-discover   = { path = "crates/solti-discover",   version = "0.0.3" }
solti-observe    = { path = "crates/solti-observe",    version = "0.0.3" }
solti-prometheus = { path = "crates/solti-prometheus", version = "0.0.3" }
