//! Attempt-scoped containerd output pipes.

#[cfg(target_os = "linux")]
mod platform {
    use std::{
        ffi::CString,
        fs::{self, File, OpenOptions, Permissions},
        io,
        os::unix::{
            ffi::OsStrExt,
            fs::{FileTypeExt, MetadataExt, OpenOptionsExt, PermissionsExt},
        },
        panic::{AssertUnwindSafe, catch_unwind},
        path::{Component, Path, PathBuf},
    };

    use tempfile::{Builder, TempDir};

    use crate::container::ContainerOutput;

    const DIRECTORY_MODE: u32 = 0o700;
    const FIFO_MODE: u32 = 0o600;

    /// Output pipes owned by one containerd attempt.
    ///
    /// The read ends stay open while containerd creates the task.
    /// This allows the shim to open the write ends without blocking.
    pub(in crate::container::containerd) struct AttemptIo {
        /// FIFO path passed to containerd for standard output.
        stdout_path: PathBuf,
        /// FIFO path passed to containerd for standard error.
        stderr_path: PathBuf,
        /// Standard output descriptor retained before activation.
        stdout_reader: Option<File>,
        /// Standard error descriptor retained before activation.
        stderr_reader: Option<File>,
        /// Activated asynchronous standard output stream.
        stdout: Option<ContainerOutput>,
        /// Activated asynchronous standard error stream.
        stderr: Option<ContainerOutput>,
        /// Whether both descriptors were transferred to asynchronous streams.
        activated: bool,
        /// Private directory retained until confirmed removal.
        directory: Option<TempDir>,
        /// Test root that keeps the private directory alive.
        #[cfg(test)]
        _test_root: Option<TempDir>,
        /// Injected blocking cleanup failure used by ownership tests.
        #[cfg(test)]
        cleanup_error: Option<io::ErrorKind>,
    }

    /// Preparation failure with any local resources that still need cleanup.
    pub(in crate::container::containerd) struct AttemptIoPrepareError {
        /// Filesystem failure that stopped preparation.
        error: io::Error,
        /// Partial attempt owner created before the failure.
        residual: Option<Box<AttemptIo>>,
    }

    impl AttemptIoPrepareError {
        /// Splits the failure into its source and optional residual owner.
        pub(in crate::container::containerd) fn into_parts(self) -> (io::Error, Option<AttemptIo>) {
            (self.error, self.residual.map(|residual| *residual))
        }
    }

    impl From<io::Error> for AttemptIoPrepareError {
        fn from(error: io::Error) -> Self {
            Self {
                error,
                residual: None,
            }
        }
    }

    impl AttemptIo {
        /// Creates private FIFOs beneath the configured output root.
        ///
        /// `attempt_id` is deliberately not used as a path component.
        /// The temporary directory name is generated by `tempfile`.
        #[cfg(test)]
        pub(in crate::container::containerd) fn prepare(
            root: &Path,
            attempt_id: &str,
        ) -> io::Result<Self> {
            Self::prepare_retained(root, attempt_id).map_err(|failure| {
                let (error, mut residual) = failure.into_parts();
                if let Some(residual) = residual.as_mut() {
                    let _ = residual.cleanup_blocking();
                }
                error
            })
        }

        /// Prepares output pipes and preserves partial ownership on failure.
        pub(in crate::container::containerd) fn prepare_retained(
            root: &Path,
            _attempt_id: &str,
        ) -> Result<Self, AttemptIoPrepareError> {
            let root = fs::canonicalize(root)?;
            validate_shared_root(&root)?;
            let directory = Builder::new()
                .prefix("solti-containerd-")
                .tempdir_in(&root)?;
            let stdout_path = directory.path().join("stdout");
            let stderr_path = directory.path().join("stderr");
            let mut attempt = Self {
                stdout_path,
                stderr_path,
                stdout_reader: None,
                stderr_reader: None,
                stdout: None,
                stderr: None,
                activated: false,
                directory: Some(directory),
                #[cfg(test)]
                _test_root: None,
                #[cfg(test)]
                cleanup_error: None,
            };
            let result = (|| {
                let directory = attempt
                    .directory
                    .as_ref()
                    .expect("attempt directory exists during preparation");
                fs::set_permissions(directory.path(), Permissions::from_mode(DIRECTORY_MODE))?;
                create_fifo(&attempt.stdout_path)?;
                create_fifo(&attempt.stderr_path)?;
                attempt.stdout_reader = Some(open_fifo_reader(&attempt.stdout_path)?);
                attempt.stderr_reader = Some(open_fifo_reader(&attempt.stderr_path)?);
                Ok(())
            })();
            match result {
                Ok(()) => Ok(attempt),
                Err(error) => Err(AttemptIoPrepareError {
                    error,
                    residual: Some(Box::new(attempt)),
                }),
            }
        }

        #[cfg(test)]
        pub(in crate::container::containerd) fn for_test() -> Self {
            let root = tempfile::TempDir::new().expect("test output root must be created");
            let mut attempt =
                Self::prepare(root.path(), "test-attempt").expect("test output must be prepared");
            attempt._test_root = Some(root);
            attempt
        }

        /// Creates test I/O whose blocking cleanup always fails.
        #[cfg(test)]
        pub(in crate::container::containerd) fn for_test_with_cleanup_error(
            kind: io::ErrorKind,
        ) -> Self {
            let mut attempt = Self::for_test();
            attempt.cleanup_error = Some(kind);
            attempt
        }

        /// Returns the FIFO path passed to `CreateTask.stdout`.
        pub(in crate::container::containerd) fn stdout_path(&self) -> &Path {
            &self.stdout_path
        }

        /// Returns the FIFO path passed to `CreateTask.stderr`.
        pub(in crate::container::containerd) fn stderr_path(&self) -> &Path {
            &self.stderr_path
        }

        /// Registers both non-blocking FIFO readers with the Tokio I/O driver.
        ///
        /// # Errors
        ///
        /// Returns an error when no Tokio runtime is active, its I/O driver is
        /// unavailable, or either reader cannot be registered.
        pub(in crate::container::containerd) fn activate(&mut self) -> io::Result<()> {
            if self.activated {
                return Ok(());
            }

            tokio::runtime::Handle::try_current().map_err(|_| missing_io_driver())?;

            let stdout = self.stdout_reader.take().ok_or_else(closed_error)?;
            let stderr = self.stderr_reader.take().ok_or_else(closed_error)?;
            self.stdout = Some(Box::pin(register_reader(stdout)?));
            self.stderr = Some(Box::pin(register_reader(stderr)?));
            self.activated = true;
            Ok(())
        }

        /// Takes the activated stdout stream.
        pub(in crate::container::containerd) fn take_stdout(&mut self) -> Option<ContainerOutput> {
            self.stdout.take()
        }

        /// Takes the activated stderr stream.
        pub(in crate::container::containerd) fn take_stderr(&mut self) -> Option<ContainerOutput> {
            self.stderr.take()
        }

        /// Closes the streams and removes only this attempt's directory.
        ///
        /// This method performs blocking filesystem work. The containerd I/O
        /// domain is its only production caller.
        pub(in crate::container::containerd) fn cleanup_blocking(&mut self) -> io::Result<()> {
            #[cfg(test)]
            if let Some(kind) = self.cleanup_error {
                return Err(io::Error::new(kind, "injected attempt I/O cleanup failure"));
            }
            self.stdout.take();
            self.stderr.take();
            self.stdout_reader.take();
            self.stderr_reader.take();

            let Some(path) = self
                .directory
                .as_ref()
                .map(|directory| directory.path().to_path_buf())
            else {
                return Ok(());
            };
            match fs::remove_dir_all(path) {
                Ok(()) => {
                    let directory = self
                        .directory
                        .take()
                        .expect("attempt directory exists until cleanup succeeds");
                    let _ = directory.keep();
                    Ok(())
                }
                Err(error) if error.kind() == io::ErrorKind::NotFound => {
                    let directory = self
                        .directory
                        .take()
                        .expect("attempt directory exists until cleanup succeeds");
                    let _ = directory.keep();
                    Ok(())
                }
                Err(error) => Err(error),
            }
        }
    }

    fn validate_shared_root(root: &Path) -> io::Result<()> {
        // SAFETY:
        // `geteuid` has no preconditions and does not access caller-owned memory.
        let effective_uid = unsafe { libc::geteuid() };
        let mut current = PathBuf::new();

        for component in root.components() {
            match component {
                Component::RootDir => current.push(component.as_os_str()),
                Component::Normal(value) => current.push(value),
                _ => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        format!(
                            "containerd I/O root is not a normalized absolute path: {}",
                            root.display()
                        ),
                    ));
                }
            }

            let metadata = fs::symlink_metadata(&current)?;
            if !metadata.is_dir() || metadata.file_type().is_symlink() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!(
                        "containerd I/O path component is not a real directory: {}",
                        current.display()
                    ),
                ));
            }
            if metadata.uid() != 0 && metadata.uid() != effective_uid {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!(
                        "containerd I/O path component has an untrusted owner: {}",
                        current.display()
                    ),
                ));
            }

            let mode = metadata.permissions().mode();
            if mode & 0o022 != 0 && mode & 0o1000 == 0 {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!(
                        "writable containerd I/O path component has no sticky bit: {}",
                        current.display()
                    ),
                ));
            }
        }

        Ok(())
    }

    fn create_fifo(path: &Path) -> io::Result<()> {
        let c_path = CString::new(path.as_os_str().as_bytes())
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "FIFO path contains NUL"))?;

        // SAFETY:
        // `c_path` is a valid NUL-terminated string and remains alive for the call.
        if unsafe { libc::mkfifo(c_path.as_ptr(), FIFO_MODE as libc::mode_t) } == -1 {
            return Err(io::Error::last_os_error());
        }

        fs::set_permissions(path, Permissions::from_mode(FIFO_MODE))
    }

    fn open_fifo_reader(path: &Path) -> io::Result<File> {
        let file = OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_NONBLOCK | libc::O_NOFOLLOW)
            .open(path)?;
        let metadata = file.metadata()?;
        if !metadata.file_type().is_fifo() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("output path is not a FIFO: {}", path.display()),
            ));
        }
        if metadata.permissions().mode() & 0o777 != FIFO_MODE {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                format!("output FIFO has unexpected permissions: {}", path.display()),
            ));
        }
        Ok(file)
    }

    fn closed_error() -> io::Error {
        io::Error::new(
            io::ErrorKind::BrokenPipe,
            "container output pipes are closed",
        )
    }

    /// Registers one descriptor without exposing Tokio's missing-driver panic.
    fn register_reader(reader: File) -> io::Result<tokio::net::unix::pipe::Receiver> {
        catch_unwind(AssertUnwindSafe(|| {
            tokio::net::unix::pipe::Receiver::from_file(reader)
        }))
        .map_err(|_| missing_io_driver())?
    }

    /// Creates the stable error for a missing Tokio I/O driver.
    fn missing_io_driver() -> io::Error {
        io::Error::other("Tokio I/O driver is unavailable for containerd output")
    }

    #[cfg(test)]
    mod tests {
        use std::{
            fs::{self, File, OpenOptions},
            io::{self, Write},
            os::unix::{
                fs::{FileTypeExt, OpenOptionsExt, PermissionsExt},
                io::{AsRawFd, FromRawFd},
            },
        };

        use tokio::io::AsyncReadExt;

        use super::{AttemptIo, DIRECTORY_MODE, FIFO_MODE};

        #[test]
        fn prepare_creates_private_attempt_directory_and_fifos() {
            let root = tempfile::TempDir::new().unwrap();
            let attempt = AttemptIo::prepare(root.path(), "../../untrusted/attempt").unwrap();
            let directory = attempt.stdout_path().parent().unwrap();

            assert_eq!(directory.parent(), Some(root.path()));
            assert_eq!(
                fs::metadata(directory).unwrap().permissions().mode() & 0o777,
                DIRECTORY_MODE
            );
            for path in [attempt.stdout_path(), attempt.stderr_path()] {
                let metadata = fs::metadata(path).unwrap();
                assert!(metadata.file_type().is_fifo());
                assert_eq!(metadata.permissions().mode() & 0o777, FIFO_MODE);
            }
            assert!(is_nonblocking(attempt.stdout_reader.as_ref().unwrap()).unwrap());
            assert!(is_nonblocking(attempt.stderr_reader.as_ref().unwrap()).unwrap());
        }

        #[test]
        fn activate_without_tokio_runtime_returns_an_error() {
            let root = tempfile::TempDir::new().unwrap();
            let mut attempt = AttemptIo::prepare(root.path(), "attempt-1").unwrap();

            let error = attempt.activate().unwrap_err();

            assert_eq!(error.kind(), io::ErrorKind::Other);
            assert!(error.to_string().contains("Tokio I/O driver"));
            assert!(attempt.stdout_reader.is_some());
            assert!(attempt.stderr_reader.is_some());
        }

        #[tokio::test]
        async fn activate_keeps_nonblocking_and_exposes_streams() {
            let root = tempfile::TempDir::new().unwrap();
            let mut attempt = AttemptIo::prepare(root.path(), "attempt-1").unwrap();
            let mut writer = OpenOptions::new()
                .write(true)
                .custom_flags(libc::O_NONBLOCK)
                .open(attempt.stdout_path())
                .unwrap();
            let mut error_writer = OpenOptions::new()
                .write(true)
                .custom_flags(libc::O_NONBLOCK)
                .open(attempt.stderr_path())
                .unwrap();
            let observer = duplicate(attempt.stdout_reader.as_ref().unwrap()).unwrap();

            attempt.activate().unwrap();
            attempt.activate().unwrap();
            assert!(is_nonblocking(&observer).unwrap());

            writer.write_all(b"hello\n").unwrap();
            error_writer.write_all(b"failed\n").unwrap();
            drop(writer);
            drop(error_writer);
            let mut stdout = attempt.take_stdout().unwrap();
            let mut stderr = attempt.take_stderr().unwrap();
            let mut stdout_bytes = Vec::new();
            let mut stderr_bytes = Vec::new();
            stdout.read_to_end(&mut stdout_bytes).await.unwrap();
            stderr.read_to_end(&mut stderr_bytes).await.unwrap();
            assert_eq!(stdout_bytes, b"hello\n");
            assert_eq!(stderr_bytes, b"failed\n");
            assert!(attempt.take_stdout().is_none());
            assert!(attempt.take_stderr().is_none());
        }

        #[test]
        fn cleanup_is_idempotent_and_keeps_sibling_files() {
            let root = tempfile::TempDir::new().unwrap();
            let sibling = root.path().join("keep");
            fs::write(&sibling, b"owned by caller").unwrap();
            let mut attempt = AttemptIo::prepare(root.path(), "attempt-1").unwrap();
            let directory = attempt.stdout_path().parent().unwrap().to_path_buf();

            attempt.cleanup_blocking().unwrap();
            attempt.cleanup_blocking().unwrap();

            assert!(!directory.exists());
            assert_eq!(fs::read(sibling).unwrap(), b"owned by caller");
        }

        #[test]
        fn prepare_rejects_a_replaceable_shared_root() {
            let parent = tempfile::TempDir::new().unwrap();
            let root = parent.path().join("shared");
            fs::create_dir(&root).unwrap();
            fs::set_permissions(&root, fs::Permissions::from_mode(0o777)).unwrap();

            let error = match AttemptIo::prepare(&root, "attempt-1") {
                Ok(_) => panic!("replaceable root must be rejected"),
                Err(error) => error,
            };

            assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
            assert!(error.to_string().contains("has no sticky bit"));
        }

        #[test]
        fn prepare_accepts_a_sticky_shared_root() {
            let parent = tempfile::TempDir::new().unwrap();
            let root = parent.path().join("shared");
            fs::create_dir(&root).unwrap();
            fs::set_permissions(&root, fs::Permissions::from_mode(0o1777)).unwrap();

            let mut attempt = AttemptIo::prepare(&root, "attempt-1").unwrap();

            attempt.cleanup_blocking().unwrap();
        }

        #[test]
        fn prepare_rejects_a_replaceable_shared_ancestor() {
            let parent = tempfile::TempDir::new().unwrap();
            let shared = parent.path().join("shared");
            let root = shared.join("root");
            fs::create_dir(&shared).unwrap();
            fs::create_dir(&root).unwrap();
            fs::set_permissions(&shared, fs::Permissions::from_mode(0o777)).unwrap();

            let error = match AttemptIo::prepare(&root, "attempt-1") {
                Ok(_) => panic!("replaceable ancestor must be rejected"),
                Err(error) => error,
            };

            assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
            assert!(error.to_string().contains("has no sticky bit"));
        }

        fn is_nonblocking(file: &File) -> io::Result<bool> {
            // SAFETY: the descriptor belongs to `file` and stays valid for the call.
            let flags = unsafe { libc::fcntl(file.as_raw_fd(), libc::F_GETFL) };
            if flags == -1 {
                Err(io::Error::last_os_error())
            } else {
                Ok(flags & libc::O_NONBLOCK != 0)
            }
        }

        fn duplicate(file: &File) -> io::Result<File> {
            // SAFETY: the descriptor belongs to `file` and stays valid for the call.
            let descriptor = unsafe { libc::dup(file.as_raw_fd()) };
            if descriptor == -1 {
                return Err(io::Error::last_os_error());
            }
            // SAFETY: `dup` returned a new descriptor owned by this `File`.
            Ok(unsafe { File::from_raw_fd(descriptor) })
        }
    }
}

#[cfg(not(target_os = "linux"))]
mod platform {
    use std::{io, path::Path};

    #[cfg(test)]
    use std::path::PathBuf;

    use crate::container::ContainerOutput;

    /// Placeholder that keeps the native adapter compile-safe off Linux.
    pub(in crate::container::containerd) struct AttemptIo {
        /// Test path returned as standard output.
        #[cfg(test)]
        stdout_path: PathBuf,
        /// Test path returned as standard error.
        #[cfg(test)]
        stderr_path: PathBuf,
        /// Injected blocking cleanup failure used by ownership tests.
        #[cfg(test)]
        cleanup_error: Option<io::ErrorKind>,
    }

    /// Preparation failure without platform-local resources.
    pub(in crate::container::containerd) struct AttemptIoPrepareError {
        /// Platform error that rejected preparation.
        error: io::Error,
    }

    impl AttemptIoPrepareError {
        /// Splits the failure into its source and absent residual owner.
        pub(in crate::container::containerd) fn into_parts(self) -> (io::Error, Option<AttemptIo>) {
            (self.error, None)
        }
    }

    impl AttemptIo {
        /// Rejects native output preparation on unsupported platforms.
        pub(in crate::container::containerd) fn prepare_retained(
            _root: &Path,
            _attempt_id: &str,
        ) -> Result<Self, AttemptIoPrepareError> {
            Err(AttemptIoPrepareError {
                error: io::Error::new(
                    io::ErrorKind::Unsupported,
                    "native containerd output pipes require Linux",
                ),
            })
        }

        #[cfg(test)]
        /// Creates inert attempt I/O for platform-neutral lifecycle tests.
        pub(in crate::container::containerd) fn for_test() -> Self {
            Self {
                stdout_path: PathBuf::from("/test/stdout"),
                stderr_path: PathBuf::from("/test/stderr"),
                cleanup_error: None,
            }
        }

        /// Creates inert test I/O whose cleanup always fails.
        #[cfg(test)]
        pub(in crate::container::containerd) fn for_test_with_cleanup_error(
            kind: io::ErrorKind,
        ) -> Self {
            Self {
                stdout_path: PathBuf::from("/test/stdout"),
                stderr_path: PathBuf::from("/test/stderr"),
                cleanup_error: Some(kind),
            }
        }

        /// Returns the standard output path.
        pub(in crate::container::containerd) fn stdout_path(&self) -> &Path {
            #[cfg(test)]
            {
                &self.stdout_path
            }
            #[cfg(not(test))]
            {
                Path::new("")
            }
        }

        /// Returns the standard error path.
        pub(in crate::container::containerd) fn stderr_path(&self) -> &Path {
            #[cfg(test)]
            {
                &self.stderr_path
            }
            #[cfg(not(test))]
            {
                Path::new("")
            }
        }

        /// Activates inert test streams or rejects production use.
        pub(in crate::container::containerd) fn activate(&mut self) -> io::Result<()> {
            #[cfg(test)]
            {
                Ok(())
            }
            #[cfg(not(test))]
            {
                Err(io::Error::new(
                    io::ErrorKind::Unsupported,
                    "native containerd output pipes require Linux",
                ))
            }
        }

        /// Takes the unavailable standard output stream.
        pub(in crate::container::containerd) fn take_stdout(&mut self) -> Option<ContainerOutput> {
            None
        }

        /// Takes the unavailable standard error stream.
        pub(in crate::container::containerd) fn take_stderr(&mut self) -> Option<ContainerOutput> {
            None
        }

        /// Completes inert blocking cleanup.
        pub(in crate::container::containerd) fn cleanup_blocking(&mut self) -> io::Result<()> {
            #[cfg(test)]
            if let Some(kind) = self.cleanup_error {
                return Err(io::Error::new(kind, "injected attempt I/O cleanup failure"));
            }
            Ok(())
        }
    }
}

pub(super) use platform::AttemptIo;
