//! Attempt-scoped containerd output pipes.

#[cfg(target_os = "linux")]
mod platform {
    use std::{
        ffi::CString,
        fs::{self, File, OpenOptions, Permissions},
        io,
        os::unix::{
            ffi::OsStrExt,
            fs::{FileTypeExt, MetadataExt, OpenOptionsExt, PermissionsExt},
            io::AsRawFd,
        },
        path::{Component, Path, PathBuf},
    };

    use tempfile::{Builder, TempDir};

    use crate::container::ContainerOutput;

    const DIRECTORY_MODE: u32 = 0o700;
    const FIFO_MODE: u32 = 0o600;

    /// Output pipes owned by one containerd attempt.
    ///
    /// The read ends stay open while containerd creates the task.
    /// This allows the shim to open the write ends without blocking.
    pub(in crate::container::containerd) struct AttemptIo {
        stdout_path: PathBuf,
        stderr_path: PathBuf,
        stdout_reader: Option<File>,
        stderr_reader: Option<File>,
        stdout: Option<ContainerOutput>,
        stderr: Option<ContainerOutput>,
        activated: bool,
        directory: Option<TempDir>,
    }

    impl AttemptIo {
        /// Creates private FIFOs beneath the configured output root.
        ///
        /// `attempt_id` is deliberately not used as a path component.
        /// The temporary directory name is generated by `tempfile`.
        pub(in crate::container::containerd) fn prepare(
            root: &Path,
            _attempt_id: &str,
        ) -> io::Result<Self> {
            let root = fs::canonicalize(root)?;
            validate_shared_root(&root)?;
            let directory = Builder::new()
                .prefix("solti-containerd-")
                .tempdir_in(&root)?;
            fs::set_permissions(directory.path(), Permissions::from_mode(DIRECTORY_MODE))?;

            let stdout_path = directory.path().join("stdout");
            let stderr_path = directory.path().join("stderr");
            create_fifo(&stdout_path)?;
            create_fifo(&stderr_path)?;

            let stdout_reader = open_fifo_reader(&stdout_path)?;
            let stderr_reader = open_fifo_reader(&stderr_path)?;

            Ok(Self {
                stdout_path,
                stderr_path,
                stdout_reader: Some(stdout_reader),
                stderr_reader: Some(stderr_reader),
                stdout: None,
                stderr: None,
                activated: false,
                directory: Some(directory),
            })
        }

        /// Returns the FIFO path passed to `CreateTask.stdout`.
        pub(in crate::container::containerd) fn stdout_path(&self) -> &Path {
            &self.stdout_path
        }

        /// Returns the FIFO path passed to `CreateTask.stderr`.
        pub(in crate::container::containerd) fn stderr_path(&self) -> &Path {
            &self.stderr_path
        }

        /// Switches the read ends to blocking mode after `CreateTask` succeeds.
        ///
        /// Tokio moves blocking file reads to its blocking thread pool.
        pub(in crate::container::containerd) fn activate(&mut self) -> io::Result<()> {
            if self.activated {
                return Ok(());
            }

            let stdout = self.stdout_reader.as_ref().ok_or_else(closed_error)?;
            let stderr = self.stderr_reader.as_ref().ok_or_else(closed_error)?;
            clear_nonblocking(stdout)?;
            clear_nonblocking(stderr)?;

            let stdout = self.stdout_reader.take().ok_or_else(closed_error)?;
            let stderr = self.stderr_reader.take().ok_or_else(closed_error)?;
            self.stdout = Some(Box::pin(tokio::fs::File::from_std(stdout)));
            self.stderr = Some(Box::pin(tokio::fs::File::from_std(stderr)));
            self.activated = true;
            Ok(())
        }

        /// Takes the activated stdout stream.
        pub(in crate::container::containerd) fn take_stdout(&mut self) -> Option<ContainerOutput> {
            self.stdout.take()
        }

        /// Takes the activated stderr stream.
        pub(in crate::container::containerd) fn take_stderr(&mut self) -> Option<ContainerOutput> {
            self.stderr.take()
        }

        /// Closes the streams and removes only this attempt's directory.
        pub(in crate::container::containerd) fn cleanup(&mut self) -> io::Result<()> {
            self.stdout.take();
            self.stderr.take();
            self.stdout_reader.take();
            self.stderr_reader.take();

            let Some(directory) = self.directory.take() else {
                return Ok(());
            };
            match fs::remove_dir_all(directory.path()) {
                Ok(()) => {
                    let _ = directory.keep();
                    Ok(())
                }
                Err(error) if error.kind() == io::ErrorKind::NotFound => {
                    let _ = directory.keep();
                    Ok(())
                }
                Err(error) => {
                    self.directory = Some(directory);
                    Err(error)
                }
            }
        }
    }

    fn validate_shared_root(root: &Path) -> io::Result<()> {
        // SAFETY:
        // `geteuid` has no preconditions and does not access caller-owned memory.
        let effective_uid = unsafe { libc::geteuid() };
        let mut current = PathBuf::new();

        for component in root.components() {
            match component {
                Component::RootDir => current.push(component.as_os_str()),
                Component::Normal(value) => current.push(value),
                _ => {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidInput,
                        format!(
                            "containerd I/O root is not a normalized absolute path: {}",
                            root.display()
                        ),
                    ));
                }
            }

            let metadata = fs::symlink_metadata(&current)?;
            if !metadata.is_dir() || metadata.file_type().is_symlink() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!(
                        "containerd I/O path component is not a real directory: {}",
                        current.display()
                    ),
                ));
            }
            if metadata.uid() != 0 && metadata.uid() != effective_uid {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!(
                        "containerd I/O path component has an untrusted owner: {}",
                        current.display()
                    ),
                ));
            }

            let mode = metadata.permissions().mode();
            if mode & 0o022 != 0 && mode & 0o1000 == 0 {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    format!(
                        "writable containerd I/O path component has no sticky bit: {}",
                        current.display()
                    ),
                ));
            }
        }

        Ok(())
    }

    fn create_fifo(path: &Path) -> io::Result<()> {
        let c_path = CString::new(path.as_os_str().as_bytes())
            .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "FIFO path contains NUL"))?;

        // SAFETY:
        // `c_path` is a valid NUL-terminated string and remains alive for the call.
        if unsafe { libc::mkfifo(c_path.as_ptr(), FIFO_MODE as libc::mode_t) } == -1 {
            return Err(io::Error::last_os_error());
        }

        fs::set_permissions(path, Permissions::from_mode(FIFO_MODE))
    }

    fn open_fifo_reader(path: &Path) -> io::Result<File> {
        let file = OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_NONBLOCK | libc::O_NOFOLLOW)
            .open(path)?;
        let metadata = file.metadata()?;
        if !metadata.file_type().is_fifo() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("output path is not a FIFO: {}", path.display()),
            ));
        }
        if metadata.permissions().mode() & 0o777 != FIFO_MODE {
            return Err(io::Error::new(
                io::ErrorKind::PermissionDenied,
                format!("output FIFO has unexpected permissions: {}", path.display()),
            ));
        }
        Ok(file)
    }

    fn clear_nonblocking(file: &File) -> io::Result<()> {
        let descriptor = file.as_raw_fd();
        // SAFETY:
        // `descriptor` is owned by `file` and remains valid for both calls.
        let flags = unsafe { libc::fcntl(descriptor, libc::F_GETFL) };
        if flags == -1 {
            return Err(io::Error::last_os_error());
        }
        // SAFETY:
        // `descriptor` remains valid and `flags` came from `F_GETFL`.
        if unsafe { libc::fcntl(descriptor, libc::F_SETFL, flags & !libc::O_NONBLOCK) } == -1 {
            return Err(io::Error::last_os_error());
        }
        Ok(())
    }

    fn closed_error() -> io::Error {
        io::Error::new(
            io::ErrorKind::BrokenPipe,
            "container output pipes are closed",
        )
    }

    #[cfg(test)]
    mod tests {
        use std::{
            fs::{self, File, OpenOptions},
            io::{self, Write},
            os::unix::{
                fs::{FileTypeExt, OpenOptionsExt, PermissionsExt},
                io::{AsRawFd, FromRawFd},
            },
        };

        use tokio::io::AsyncReadExt;

        use super::{AttemptIo, DIRECTORY_MODE, FIFO_MODE};

        #[test]
        fn prepare_creates_private_attempt_directory_and_fifos() {
            let root = tempfile::TempDir::new().unwrap();
            let attempt = AttemptIo::prepare(root.path(), "../../untrusted/attempt").unwrap();
            let directory = attempt.stdout_path().parent().unwrap();

            assert_eq!(directory.parent(), Some(root.path()));
            assert_eq!(
                fs::metadata(directory).unwrap().permissions().mode() & 0o777,
                DIRECTORY_MODE
            );
            for path in [attempt.stdout_path(), attempt.stderr_path()] {
                let metadata = fs::metadata(path).unwrap();
                assert!(metadata.file_type().is_fifo());
                assert_eq!(metadata.permissions().mode() & 0o777, FIFO_MODE);
            }
            assert!(is_nonblocking(attempt.stdout_reader.as_ref().unwrap()).unwrap());
            assert!(is_nonblocking(attempt.stderr_reader.as_ref().unwrap()).unwrap());
        }

        #[tokio::test]
        async fn activate_clears_nonblocking_and_exposes_streams() {
            let root = tempfile::TempDir::new().unwrap();
            let mut attempt = AttemptIo::prepare(root.path(), "attempt-1").unwrap();
            let mut writer = OpenOptions::new()
                .write(true)
                .custom_flags(libc::O_NONBLOCK)
                .open(attempt.stdout_path())
                .unwrap();
            let mut error_writer = OpenOptions::new()
                .write(true)
                .custom_flags(libc::O_NONBLOCK)
                .open(attempt.stderr_path())
                .unwrap();
            let observer = duplicate(attempt.stdout_reader.as_ref().unwrap()).unwrap();

            attempt.activate().unwrap();
            attempt.activate().unwrap();
            assert!(!is_nonblocking(&observer).unwrap());

            writer.write_all(b"hello\n").unwrap();
            error_writer.write_all(b"failed\n").unwrap();
            drop(writer);
            drop(error_writer);
            let mut stdout = attempt.take_stdout().unwrap();
            let mut stderr = attempt.take_stderr().unwrap();
            let mut stdout_bytes = Vec::new();
            let mut stderr_bytes = Vec::new();
            stdout.read_to_end(&mut stdout_bytes).await.unwrap();
            stderr.read_to_end(&mut stderr_bytes).await.unwrap();
            assert_eq!(stdout_bytes, b"hello\n");
            assert_eq!(stderr_bytes, b"failed\n");
            assert!(attempt.take_stdout().is_none());
            assert!(attempt.take_stderr().is_none());
        }

        #[test]
        fn cleanup_is_idempotent_and_keeps_sibling_files() {
            let root = tempfile::TempDir::new().unwrap();
            let sibling = root.path().join("keep");
            fs::write(&sibling, b"owned by caller").unwrap();
            let mut attempt = AttemptIo::prepare(root.path(), "attempt-1").unwrap();
            let directory = attempt.stdout_path().parent().unwrap().to_path_buf();

            attempt.cleanup().unwrap();
            attempt.cleanup().unwrap();

            assert!(!directory.exists());
            assert_eq!(fs::read(sibling).unwrap(), b"owned by caller");
        }

        #[test]
        fn prepare_rejects_a_replaceable_shared_root() {
            let parent = tempfile::TempDir::new().unwrap();
            let root = parent.path().join("shared");
            fs::create_dir(&root).unwrap();
            fs::set_permissions(&root, fs::Permissions::from_mode(0o777)).unwrap();

            let error = match AttemptIo::prepare(&root, "attempt-1") {
                Ok(_) => panic!("replaceable root must be rejected"),
                Err(error) => error,
            };

            assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
            assert!(error.to_string().contains("has no sticky bit"));
        }

        #[test]
        fn prepare_accepts_a_sticky_shared_root() {
            let parent = tempfile::TempDir::new().unwrap();
            let root = parent.path().join("shared");
            fs::create_dir(&root).unwrap();
            fs::set_permissions(&root, fs::Permissions::from_mode(0o1777)).unwrap();

            let mut attempt = AttemptIo::prepare(&root, "attempt-1").unwrap();

            attempt.cleanup().unwrap();
        }

        #[test]
        fn prepare_rejects_a_replaceable_shared_ancestor() {
            let parent = tempfile::TempDir::new().unwrap();
            let shared = parent.path().join("shared");
            let root = shared.join("root");
            fs::create_dir(&shared).unwrap();
            fs::create_dir(&root).unwrap();
            fs::set_permissions(&shared, fs::Permissions::from_mode(0o777)).unwrap();

            let error = match AttemptIo::prepare(&root, "attempt-1") {
                Ok(_) => panic!("replaceable ancestor must be rejected"),
                Err(error) => error,
            };

            assert_eq!(error.kind(), io::ErrorKind::PermissionDenied);
            assert!(error.to_string().contains("has no sticky bit"));
        }

        fn is_nonblocking(file: &File) -> io::Result<bool> {
            // SAFETY: the descriptor belongs to `file` and stays valid for the call.
            let flags = unsafe { libc::fcntl(file.as_raw_fd(), libc::F_GETFL) };
            if flags == -1 {
                Err(io::Error::last_os_error())
            } else {
                Ok(flags & libc::O_NONBLOCK != 0)
            }
        }

        fn duplicate(file: &File) -> io::Result<File> {
            // SAFETY: the descriptor belongs to `file` and stays valid for the call.
            let descriptor = unsafe { libc::dup(file.as_raw_fd()) };
            if descriptor == -1 {
                return Err(io::Error::last_os_error());
            }
            // SAFETY: `dup` returned a new descriptor owned by this `File`.
            Ok(unsafe { File::from_raw_fd(descriptor) })
        }
    }
}

#[cfg(not(target_os = "linux"))]
mod platform {
    use std::{io, path::Path};

    use crate::container::ContainerOutput;

    /// Placeholder that keeps the native adapter compile-safe off Linux.
    pub(in crate::container::containerd) struct AttemptIo;

    impl AttemptIo {
        pub(in crate::container::containerd) fn prepare(
            _root: &Path,
            _attempt_id: &str,
        ) -> io::Result<Self> {
            Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "native containerd output pipes require Linux",
            ))
        }

        pub(in crate::container::containerd) fn stdout_path(&self) -> &Path {
            Path::new("")
        }

        pub(in crate::container::containerd) fn stderr_path(&self) -> &Path {
            Path::new("")
        }

        pub(in crate::container::containerd) fn activate(&mut self) -> io::Result<()> {
            Err(io::Error::new(
                io::ErrorKind::Unsupported,
                "native containerd output pipes require Linux",
            ))
        }

        pub(in crate::container::containerd) fn take_stdout(&mut self) -> Option<ContainerOutput> {
            None
        }

        pub(in crate::container::containerd) fn take_stderr(&mut self) -> Option<ContainerOutput> {
            None
        }

        pub(in crate::container::containerd) fn cleanup(&mut self) -> io::Result<()> {
            Ok(())
        }
    }
}

pub(super) use platform::AttemptIo;
