[package]
name = "solti-runner"
description = "Solti SDK runner plugin trait."

rust-version.workspace = true
repository.workspace = true
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
taskvisor = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

solti-model = { workspace = true }

[dev-dependencies]
tokio-util = { workspace = true }

[package.metadata.docs.rs]
all-features = true
