[package]
name = "solti-runner"
description = "Runner plugin trait, routing, and execution metrics for the Solti task SDK."

rust-version.workspace = true
repository.workspace = true
categories = ["asynchronous", "concurrency"]
homepage.workspace = true
keywords = ["runner", "plugin", "tasks", "async", "executor"]
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
bytes       = { workspace = true }
taskvisor   = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }

solti-model = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
