//! # Task identifier.
//!
//! [`TaskId`] is a unique identifier for a task resource (newtype over `Arc<str>`).

use std::borrow::Borrow;
use std::fmt;
use std::sync::Arc;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

/// Unique identifier for a task instance.
///
/// Generated by the runner during task creation.
/// Format: `{runner}-{slot}-{seq:x}` (e.g., `subprocess-demo-slot-2a`)
///
/// ```text
///  TaskSpec { slot: "build" }
///           │
///           ▼  submit #1
///  TaskId: "subprocess-build-1"   ← attempt 1..N, then done
///           │
///           ▼  submit #2
///  TaskId: "subprocess-build-2"   ← new run, new id
///           │
///           ▼  submit #3
///  TaskId: "subprocess-build-3"
/// ```
///
/// The [`Slot`] stays the same across submissions.
/// The `TaskId` is unique per run: same slot, different execution, different id.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TaskId(Arc<str>);

impl TaskId {
    /// Create a new task ID from a string.
    #[inline]
    pub fn new(id: &str) -> Self {
        Self(Arc::from(id))
    }

    /// Get the task ID as a string slice.
    #[inline]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Convert into the underlying `Arc<str>`.
    #[inline]
    pub fn into_inner(self) -> Arc<str> {
        self.0
    }
}

impl From<String> for TaskId {
    #[inline]
    fn from(s: String) -> Self {
        Self(Arc::from(s))
    }
}

impl From<&str> for TaskId {
    #[inline]
    fn from(s: &str) -> Self {
        Self(Arc::from(s))
    }
}

impl From<Arc<str>> for TaskId {
    #[inline]
    fn from(s: Arc<str>) -> Self {
        Self(s)
    }
}

impl AsRef<str> for TaskId {
    #[inline]
    fn as_ref(&self) -> &str {
        &self.0
    }
}

impl Borrow<str> for TaskId {
    #[inline]
    fn borrow(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for TaskId {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

// Allow `==` comparisons with &str and String for ergonomics.
impl PartialEq<str> for TaskId {
    #[inline]
    fn eq(&self, other: &str) -> bool {
        &*self.0 == other
    }
}

impl PartialEq<&str> for TaskId {
    #[inline]
    fn eq(&self, other: &&str) -> bool {
        &*self.0 == *other
    }
}

impl PartialEq<String> for TaskId {
    #[inline]
    fn eq(&self, other: &String) -> bool {
        &*self.0 == other.as_str()
    }
}

// Manual serde: serialize as plain string, deserialize via String → Arc<str>.
impl Serialize for TaskId {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(&self.0)
    }
}

impl<'de> Deserialize<'de> for TaskId {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        String::deserialize(deserializer).map(|s| Self(Arc::from(s)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    #[test]
    fn task_id_from_string() {
        let id = TaskId::from("subprocess-slot-2a");
        assert_eq!(id.as_str(), "subprocess-slot-2a");
    }

    #[test]
    fn task_id_display() {
        let id = TaskId::new("test-id");
        assert_eq!(format!("{}", id), "test-id");
    }

    #[test]
    fn task_id_serde_transparent() {
        let id = TaskId::from("runner-slot-ff");
        let json = serde_json::to_string(&id).unwrap();
        assert_eq!(json, r#""runner-slot-ff""#);

        let back: TaskId = serde_json::from_str(&json).unwrap();
        assert_eq!(back, id);
    }

    #[test]
    fn task_id_hash_equality() {
        use std::collections::HashSet;

        let mut set = HashSet::new();
        set.insert(TaskId::from("id-1"));
        set.insert(TaskId::from("id-2"));
        set.insert(TaskId::from("id-1"));

        assert_eq!(set.len(), 2);
        assert!(set.contains(&TaskId::from("id-1")));
    }

    #[test]
    fn clone_is_cheap() {
        let id = TaskId::new("shared-task");
        let cloned = id.clone();
        assert!(Arc::ptr_eq(&id.0, &cloned.0));
    }
}
