[package]
name = "solti-observe"
description = "Structured logging and timezone sync for the Solti SDK."

rust-version.workspace = true
repository.workspace = true
categories = ["development-tools::debugging"]
homepage.workspace = true
keywords = ["logging", "tracing", "observability", "journald", "tasks"]
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default       = []
journald      = ["dep:tracing-journald"]
log-compat    = ["tracing-subscriber/tracing-log"]
timezone-sync = ["dep:solti-model", "dep:taskvisor"]

[dependencies]
serde              = { workspace = true, features = ["derive"] }
taskvisor          = { workspace = true, optional = true }
time               = { workspace = true, features = ["formatting", "local-offset"] }
thiserror          = { workspace = true }
tracing            = { workspace = true }
tracing-journald   = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, default-features = false, features = ["ansi", "env-filter", "json", "smallvec"] }

solti-model = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
tokio      = { workspace = true, features = ["rt", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
