[package]
name = "agentd-grpc"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
solti = { path = "../../crates/solti", features = [
    "api-core-adapter",
    "api-grpc-tls",
    "discover-grpc",
    "discover-tls",
    "exec-subprocess",
    "observe-timezone-sync",
    "prometheus-full",
    "taskvisor-tracing",
] }

tokio     = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing   = { workspace = true }
tonic     = { workspace = true, features = ["tls-ring", "transport"] }
