[package]
name = "solti-exec"
description = "Solti SDK jobs execution crate."

rust-version.workspace = true
repository.workspace = true
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
subprocess = ["dep:base64", "dep:libc", "dep:tempfile", "tokio/process"]

[dependencies]
base64 = { workspace = true, optional = true }
libc = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
tokio-util = { workspace = true }
taskvisor = { workspace = true }

solti-model = { workspace = true }
solti-runner = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[package.metadata.docs.rs]
all-features = true
