[package]
name = "agentd-http"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
solti-observe  = { path = "../../crates/solti-observe", features = ["timezone-sync", "subscriber"] }
solti-exec     = { path = "../../crates/solti-exec", features = ["subprocess"] }
solti-api      = { path = "../../crates/solti-api", features = ["http"] }
solti-discover = { path = "../../crates/solti-discover", features = ["http"] }
solti-runner   = { path = "../../crates/solti-runner" }
solti-model    = { path = "../../crates/solti-model" }
solti-core     = { path = "../../crates/solti-core" }

tokio     = { workspace = true, features = ["rt-multi-thread", "signal"] }
taskvisor = { workspace = true }
tracing   = { workspace = true }
axum      = { workspace = true }
