[package]
name = "agentd-http"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
solti = { path = "../../crates/solti", features = [
    "api-core-adapter",
    "api-http",
    "discover-http",
    "discover-tls",
    "exec-subprocess",
    "observe-timezone-sync",
    "prometheus-full",
    "taskvisor-tracing",
] }

tokio       = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing     = { workspace = true }
axum        = { workspace = true }
axum-server = { version = "0.8", features = ["tls-rustls-no-provider"] }
