[package]
name = "solti-api"
version = "0.0.1"
edition = "2024"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
grpc = ["dep:tonic", "dep:tonic-prost", "dep:prost"]
http = ["dep:axum", "dep:pbjson", "dep:prost", "dep:serde_json", "dep:tower-http"]

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
pbjson = { workspace = true, optional = true }
prost = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
solti-core = { path = "../solti-core" }
solti-model = { path = "../solti-model" }
thiserror = { workspace = true }
tonic = { workspace = true, optional = true }
tonic-prost = { workspace = true, optional = true }
tower-http = { workspace = true, features = ["limit"], optional = true }
tracing = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
http-body-util = "0.1"
tokio = { workspace = true, features = ["macros", "rt"] }
tower = { version = "0.5", features = ["util"] }

[build-dependencies]
pbjson-build = { workspace = true }
protoc-bin-vendored = { workspace = true }
tonic-prost-build = { workspace = true }
