[package]
name = "solti-model"
description = "Solti SDK domain model."

rust-version.workspace = true
repository.workspace = true
categories.workspace = true
homepage.workspace = true
keywords.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
base64    = { workspace = true }
bytes     = { workspace = true }
serde     = { workspace = true, features = ["rc"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[package.metadata.docs.rs]
all-features = true
