name: Docs

on: { workflow_call: {} }

jobs:
  crates:
    uses: ./.github/workflows/.crates.yml

  docs:
    needs: crates
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        crate: ${{ fromJSON(needs.crates.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - name: Run docs gen
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ci/docs CRATE=${{ matrix.crate }}
