name: Preflight

on: { workflow_call: {} }

jobs:
  crates:
    uses: ./.github/workflows/.crates.yml

  publish-dry-run:
    needs: crates
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        crate: ${{ fromJSON(needs.crates.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - name: Run publish dry-run
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ci:cargo/publish-dry-run CRATE=${{ matrix.crate }}
